### ISSUE TITLE
outlook windows app

### ISSUE THREAD

**Issue by andekande** [hl2guide/Filterlist-for-AdGuard#30]
The windows 10 app from the windows store won't send emails unles this rule is whitelisted:
`@@||outlook.office.com$important`

**Comment by 91ajames** [comment]
I had that link in another post and i guess he missed it to whitelist if it doesn't brake the main point of this git.
Here's some others.

Windows 10 -
@@||tile-service.weather.microsoft.com
@@||outlook.office.com
@@||blobs.officehome.msocdn.com -completely broke the windows office app

For Playstation  -
@@||playstation.com
@@||playstation.net

Another for Apple -
@@||updates-http.cdn-apple.com

Disney+ -
@@||global.edge.bamgrid.com -this brakes D+ app on the tv.

**Comment by hl2guide** [comment]
Please consider that this AIO list is aggressive.

Please take the time to whitelist properly to customize it to your liking.

Also depending on the person, the domains you're listing here would be privacy concerns (tracking).

**Comment by 91ajames** [comment]
@hl2guide Yea, I completely understand. As I said, `IF` it doesn't brake the main purpose.

Some that I whitelisted is either due to the site not working well or the changes like PlayStation has done recently.
Tiktok not playing once the site loads that the video will not play at all which AdGuard has the option under `Block Services` to restrict from accessing already along with blocking the very same url I believe. `s16.toktokcdn.com`
Some emails not loading all the way like `under-armor` to accept the images while keep blocking the ads within that same email (plus whatever trackers) along with it that some providers apply with the hidden url direct code msg's to display. In the end, I completely understand. Tracking.

For any wonders out there, I'm still testing with my own whitelist for Apple. Specially with espn. The url `b.scorecardresearch.com`
