### ISSUE TITLE
URLs ending in .br (Brazil) are being blocked

### ISSUE THREAD

**Issue by marcelloinfoweb** [hl2guide/Filterlist-for-AdGuard#50]
**Describe the bug**
Brazil URLs are being blocked.

Ex. Https://lgpd.assistemas.com.br/

**Erro Message**
Rule(s) .br

Filterlist-for-AdGuard - blocklist1

**Desktop (please complete the following information):**
- Browser all
- Version lasted
- AdGuard Home lasted

**Comment by hl2guide** [comment]
ok I'll look into this.

**Comment by marcelloinfoweb** [comment]
It is blocking whatsapp web and GitHub.

**Comment by marcelloinfoweb** [comment]
Would it be possible to make a smaller list with only them most blocked?

**Comment by hl2guide** [comment]
This list is meant to be very aggressive and blocks domains as well as TLDs (top level domains).

_In my Security Intellegence that I keep there is a big spike in malicious domains in brazil. That's why the TLD ".br" is blocked._

I'd suggest you either:

- Manually whitelist specific .br domains, if there's not many of them you visit
- For Adguard's "Custom filtering rules" add the rule: `@@||*.br` , and then be careful

**Comment by hl2guide** [comment]
> It is blocking whatsapp web and GitHub.

Is that for the Brazilian domains?
