### ISSUE TITLE
There are several rules that block too agressively

### ISSUE THREAD

**Issue by ninhnq** [hl2guide/Filterlist-for-AdGuard#53]
**Describe the bug**
**To Reproduce**
1. Go to https://community.linuxmint.com
2. Adguardhome blocks it by following the rule "omm" (in the 3rd block list)
**Expected behavior**
It should block only omm things, not \*omm\*

**Additional context**
There are many others similar rules that are annoying eg,: "stat" rule blocks statics sites just because the URL contain static.

**Comment by hl2guide** [comment]
Thanks for reporting this, I'll try to fix in the next few commits.

Preview of code changes (bottom):

![image](https://user-images.githubusercontent.com/17044982/111729806-08f25980-88c4-11eb-9421-ac4c4cd152c5.png)

As you can probably guess since this blocklist contains so much data, it's involved.

If you notice some more please add them as comments below (in this issue).

**Comment by ninhnq** [comment]
the rule id.c is blocking every domains contain *id.c*

**Comment by ninhnq** [comment]
the rule ads. is blocking every domains contain *ads.* including "downloads."

**Comment by hl2guide** [comment]
Thanks, the next commit should fix those.

**Comment by ninhnq** [comment]
the rule "id.a" is blocking lucid.app
